# Generated by Django 3.1.1 on 2020-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pomodoro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
