# Generated by Django 3.1.1 on 2020-09-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200919_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='logo',
            field=models.ImageField(upload_to='badges'),
        ),
    ]
