# Generated by Django 3.1.1 on 2020-09-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200919_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
