# Generated by Django 3.1.1 on 2020-09-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
