# Generated by Django 3.1.1 on 2020-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
