# Generated by Django 3.1.1 on 2020-09-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200929_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
