# Generated by Django 3.1.1 on 2020-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
