# Generated by Django 3.1.2 on 2020-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_house_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
