# Generated by Django 3.1.1 on 2020-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date_and_time', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
