# Generated by Django 3.1.1 on 2020-09-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(default='https://us02web.zoom.us/j/89238479481?pwd=VG5SRzZlUjBWQUpBd1NEbm4yS2Z1Zz09'),
        ),
    ]
