# Generated by Django 3.1.1 on 2020-09-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Models',
        ),
    ]
