# Generated by Django 3.1.1 on 2020-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_delete_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(upload_to='events'),
        ),
    ]
