# Generated by Django 3.1.2 on 2020-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_faq_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
