# Generated by Django 3.1.2 on 2020-10-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
