# Generated by Django 3.1.2 on 2021-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=10)),
                ('is_shown', models.BooleanField(default=True)),
                ('thumbline', models.ImageField(upload_to='goodies')),
                ('is_link', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('is_image', models.BooleanField(default=True)),
                ('hd_image', models.ImageField(blank=True, null=True, upload_to='goodies')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
